export const IMAGES_DATA: string[] = [
  '/images/1.jpg',
  '/images/2.jpg',
  '/images/3.jpg',
  '/images/4.jpg'
]

export const TEXT_DATA: string[] = [
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at est eget metus convallis tempus. Quisque sit amet placerat nisl. Proin luctus velit nec nibh rutrum consequat. Suspendisse id mauris lorem. Donec tincidunt vulputate nulla vel lacinia. Etiam sollicitudin ante eget lectus luctus, at consequat nulla commodo. Morbi luctus diam non lorem blandit luctus. Mauris consequat imperdiet felis, id mattis nulla facilisis vel. Cras sed tempor lacus, maximus posuere risus. Sed erat enim, dictum eu dui ac, dignissim scelerisque arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at est eget metus convallis tempus. Quisque sit amet placerat nisl. Proin luctus velit nec nibh rutrum consequat. Suspendisse id mauris lorem. Donec tincidunt vulputate nulla vel lacinia. Etiam sollicitudin ante eget lectus luctus, at consequat nulla commodo. Morbi luctus diam non lorem blandit luctus. Mauris consequat imperdiet felis, id mattis nulla facilisis vel. Cras sed tempor lacus, maximus posuere risus. Sed erat enim, dictum eu dui ac, dignissim scelerisque arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at est eget metus convallis tempus. Quisque sit amet placerat nisl. Proin luctus velit nec nibh rutrum consequat. Suspendisse id mauris lorem. Donec tincidunt vulputate nulla vel lacinia. Etiam sollicitudin ante eget lectus luctus, at consequat nulla commodo. Morbi luctus diam non lorem blandit luctus. Mauris consequat imperdiet felis, id mattis nulla facilisis vel. Cras sed tempor lacus, maximus posuere risus. Sed erat enim, dictum eu dui ac, dignissim scelerisque arcu.`,
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at est eget metus convallis tempus. Quisque sit amet placerat nisl. Proin luctus velit nec nibh rutrum consequat. Suspendisse id mauris lorem. Donec tincidunt vulputate nulla vel lacinia. Etiam sollicitudin ante eget lectus luctus, at consequat nulla commodo. Morbi luctus diam non lorem blandit luctus. Mauris consequat imperdiet felis, id mattis nulla facilisis vel. Cras sed tempor lacus, maximus posuere risus. Sed erat enim, dictum eu dui ac, dignissim scelerisque arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at est eget metus convallis tempus. Quisque sit amet placerat nisl. Proin luctus velit nec nibh rutrum consequat. Suspendisse id mauris lorem. Donec tincidunt vulputate nulla vel lacinia. Etiam sollicitudin ante eget lectus luctus, at consequat nulla commodo. Morbi luctus diam non lorem blandit luctus. Mauris consequat imperdiet felis, id mattis nulla facilisis vel. Cras sed tempor lacus, maximus posuere risus. Sed erat enim, dictum eu dui ac, dignissim scelerisque arcu.`,
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at est eget metus convallis tempus. Quisque sit amet placerat nisl. Proin luctus velit nec nibh rutrum consequat. Suspendisse id mauris lorem. Donec tincidunt vulputate nulla vel lacinia. Etiam sollicitudin ante eget lectus luctus, at consequat nulla commodo. Morbi luctus diam non lorem blandit luctus. Mauris consequat imperdiet felis, id mattis nulla facilisis vel. Cras sed tempor lacus, maximus posuere risus. Sed erat enim, dictum eu dui ac, dignissim scelerisque arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at est eget metus convallis tempus. Quisque sit amet placerat nisl. Proin luctus velit nec nibh rutrum consequat. Suspendisse id mauris lorem. Donec tincidunt vulputate nulla vel lacinia. Etiam sollicitudin ante eget lectus luctus, at consequat nulla commodo. Morbi luctus diam non lorem blandit luctus. Mauris consequat imperdiet felis, id mattis nulla facilisis vel. Cras sed tempor lacus, maximus posuere risus. Sed erat enim, dictum eu dui ac, dignissim scelerisque arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at est eget metus convallis tempus. Quisque sit amet placerat nisl. Proin luctus velit nec nibh rutrum consequat. Suspendisse id mauris lorem. Donec tincidunt vulputate nulla vel lacinia. Etiam sollicitudin ante eget lectus luctus, at consequat nulla commodo. Morbi luctus diam non lorem blandit luctus. Mauris consequat imperdiet felis, id mattis nulla facilisis vel. Cras sed tempor lacus, maximus posuere risus. Sed erat enim, dictum eu dui ac, dignissim scelerisque arcu.`,
]